version: '3.8'

services:
  go:
    image: diegodisant/blockchain-go-cli:${IMAGE_TAG:-latest}
    build:
      context: .
      target: builder
    container_name: go_cli
    network_mode: host
    volumes:
      - .:/app
    entrypoint: go
