version: '3.8'

services:
  go:
    image: diegodisant/blockchain-go-cli:${IMAGE_TAG:-latest}
    build:
      context: .
      target: builder
    container_name: blockchain_go_cli
    network_mode: host
    volumes:
      - .:/app
    entrypoint: go

  unit-test:
    image: diegodisant/blockchain-unit-test:${IMAGE_TAG:-latest}
    build:
      context: .
      target: builder
    container_name: blockchain_unit_test
    network_mode: host
    volumes:
      - .:/app
    entrypoint: go test -v ./test/unit/...
